import Head from "next/head";
import React, { useState } from "react";
import { Editor } from "./Editor";
import { Header } from "./Header";
import Workbench from "./Workbench";
export function DataStory() {
  const [mode, setMode] = useState('workbench')

  return <>
      <Head>
        <title>DataStory</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-full h-screen bg-vsCodeWarmGray-900">
        <Header />
        <div className="w-full h-5/6">
          {mode === 'workbench' && <Workbench setMode={setMode} />}
          {mode === 'dump' && <Editor setMode={setMode} />}
        </div>
      </div>
    </>;
}
  