import { Header } from './../components/Header';
import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import Workbench from '../components/Workbench/Workbench'
import { Server } from '../components/server'
import { NodePicker } from '../components/NodePicker';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>DataStory</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-full h-screen bg-gray-200">
        <Header />
        <div className="w-full h-5/6">
          <Workbench />
        </div>
        {/* <Server /> */}
        {/* <NodePicker /> */}

        {/* <div className="m-12 max-w-sm p-8 bg-gray-200">
          <div className=" mb-4">Hubspot Contacts</div>
          <div className="flex justify-between bg-gray-200 text-xs">
            <div className="flex px-2 rounded-t-lg border-t border-b border-gray-400 py-1 items-center space-x-2 bg-gray-50">
                          in


            </div>
            <div className="flex grow px-4 rounded-t-lg border-t border-l border-r border-gray-400 py-1 items-center space-x-2 bg-gray-50">
              config
            </div>
            <div className="flex px-4 rounded-t-lg border-t border-b border-gray-400 py-1 items-center space-x-2 bg-gray-50">
                        out

            </div>                        
          </div>
          <div className="bg-gray-50 text-red-500 p-12">OKej</div>
        </div> */}
        
      </div>
    </>
  )
}
