import { Header } from './../components/Header';
import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import Workbench from '../components/Workbench/Workbench'
import { Server } from '../components/server'
import { NodePicker } from '../components/NodePicker';
import { Table } from '../components/Table';
import { Editor } from '../components/Editor';
import { useState } from 'react';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [mode, setMode] = useState('workbench')
  return (
    <>
      <Head>
        <title>DataStory</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-full h-screen bg-vsCodeWarmGray-900">
        <Header />
        <div className="w-full h-5/6">
          {mode === 'workbench' && <Workbench setMode={setMode} />}
          {mode === 'dump' && <Editor setMode={setMode} />}
        </div>
      </div>
    </>
  )
}
